### ISSUE TITLE
When the user is approved, bring up popup

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/mobile-app#108]
When the user is approved, 

1. Send Push notification
2. When push notification is tapped or open up the app
3. bring up below screen

![Image](https://github.com/user-attachments/assets/c21360d8-c648-46af-94d1-61599a73638a)

**Comment by hsb1007** [comment]
It opens up this popup when tapping on push notification but not when the app is opened manually

**Comment by hsb1007** [comment]
Not happening (push notification works but when the app is only opened up without tapping on push notification, i do not get this popup

**Comment by tungmt** [comment]
let me think about it.
Now it can open popup when open app with notification or when user in the app the notification come then it auto open popup. For that case that use just open app it provide no clues that app can know the approved/rejected is happen.

**Comment by hsb1007** [comment]
FIXED - Ben to test
