### ISSUE TITLE
Apple login user dont populate the profile thpe

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/mobile-app#15]
See how the profile has no type (eg outdoor enthusiast)![image](https://github.com/user-attachments/assets/44f211ba-4ab5-4cd9-95bf-03e7c88485be)

**Comment by hsb1007** [comment]
New sign up didnt get the photo, name and type populated![image](https://github.com/user-attachments/assets/67065ebd-6d05-42d7-85e5-38703c0efaa8)

**Comment by tungmt** [comment]
This issue is fixed with new build: Version 1.0.0 (8)
