### ISSUE TITLE
Common interest

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/mobile-app#175]
![Image](https://github.com/user-attachments/assets/e2be8905-da55-4597-be9f-047741979f60)

![Image](https://github.com/user-attachments/assets/ffa764a7-d352-4890-8d5e-78cac9158b1c)

I am bringing these two in the view into the conversation.

1. How can we display these as context matching, not string matching

If profile you clicked is from the 'matching profile explore list' I expect every profile has this box

**Comment by adelinaenache** [comment]
We could prompt chatgpt to create this kind of description based on each user interests/likes/dislikes. But what do we do if users really have nothing in common? 

What do we do if one user likes 'chess' and another user likes "cycling" - technically this would be a shared interest for sports (and probably chat gpt would get that), but these sports don't really match.  On the other hand, if one user likes 'playing guitar' and another use likes 'playing the drums' then they really have a shared interest in music.
