### ISSUE TITLE
New sign up doesnt work at the verification stage

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/mobile-app#20]
![image](https://github.com/user-attachments/assets/dd22a3a0-e79f-44dc-8713-b1fc2024a08a)

**Comment by hsb1007** [comment]
Still the same

**Comment by hsb1007** [comment]
![image](https://github.com/user-attachments/assets/f7021235-21ed-48bc-89d3-c0474c2c3592)

**Comment by tungmt** [comment]
This issue is fixed with new build: Version 1.0.0 (8)
