### ISSUE TITLE
Updating interests and dislikes not working

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/mobile-app#23]
I cant add new item on press enter![image](https://github.com/user-attachments/assets/45d2cc15-19ea-4047-aea7-d04b4ca1e310)

**Comment by hsb1007** [comment]
I also find out it doesnt work for new users onboarding process hence no user can start the app

**Comment by hsb1007** [comment]
No my bad, it needed to be more than 3 characters.

Can we have a text saying if it is less than 3

“Your interest should be at least 3 characters long. Please try again!”

Your dislike should be at least 3 characters long. Please try again!”

**Comment by tungmt** [comment]
This issue is fixed with new build: Version 1.0.0 (8)
