### ISSUE TITLE
Re-connection to 'blocked' user

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/mobile-app#33]
Re-connection to 'blocked' user should throw a message saying "you have blocked this user, would you like to unblock and reconnect?

Right now, the "connected" screen shows up without actually creating a new message

**Comment by tungmt** [comment]
It already changed. You will never see people you blocked before again in explore list? Let me know if this is ok? @hsb1007

**Comment by hsb1007** [comment]
For now all good!
