### ISSUE TITLE
Prompt users for App Review

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/mobile-app#48]

**Comment by tungmt** [comment]
This task has no detail @hsb1007

**Comment by hsb1007** [comment]
When user opens up the app x number of times, request for app review (there are libraries for this feature)

**Comment by tungmt** [comment]
Sorry but still not get the idea of this task. Do you have any image or detail description?

**Comment by hsb1007** [comment]
Did you get a chance to look at this?

https://www.npmjs.com/package/react-native-in-app-review

**Comment by tungmt** [comment]
We have it work, but you need to kill the app, then open again 10 times. May be too much!

**Comment by tungmt** [comment]
@hsb1007 We have it work, but you need to kill the app, then open again 10 times. May be too much!

**Comment by tungmt** [comment]
I change it to 5 times next build

**Comment by hsb1007** [comment]
hmm for some reason it doesn't come up
