### ISSUE TITLE
Changing subscription impossible

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/mobile-app#63]
Please implement this feature

![image](https://github.com/user-attachments/assets/6c0ebfdf-9939-414f-b90d-140dade44e93)

**Comment by tungmt** [comment]
I think at this step we have only 1 plan, so it just place where we show expired date, no edit, right? @hsb1007

**Comment by hsb1007** [comment]
Edit would be how long the subscription period is!

**Comment by hsb1007** [comment]
How do we 'update the subscription'? 

UI lets me select different option but no button to save

![Image](https://github.com/user-attachments/assets/a88c57eb-806e-4db8-a398-ca7c5e5390ec)

**Comment by tungmt** [comment]
I will bring it back!
