### ISSUE TITLE
Analytics to be implemented (heatmap

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/mobile-app#68]

**Comment by tungmt** [comment]
I need detail where we need to put analytics @hsb1007

**Comment by hsb1007** [comment]
https://www.smartlook.com/

Ben to organise an access

**Comment by hsb1007** [comment]
Project Key : 6bebfbc50c0aedc486a2766bc51c24d0d2b4a13f
Documentation : [Here
](https://mobile.developer.smartlook.com/reference/react-native-sdk-installation?_gl=1*1ddjoyg*_gcl_au*MzA2MjAzODg3LjE3Mjk1OTcwNzE.*_ga*Njc5OTU2MDU5LjE3Mjk1OTcwNzI.*_ga_MJPFXC5F1G*MTcyOTU5NzA3MS4xLjEuMTcyOTU5Nzg3Mi4wLjAuMA..)

**Comment by hsb1007** [comment]
I am seeing any session, but it may take sometime, can you confirm this is implemented

**Comment by hsb1007** [comment]
I am 'NOT' seeting any session

**Comment by tungmt** [comment]
Please send me some place then I add tracking event
