### ISSUE TITLE
Force update on app

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/mobile-app#74]

**Comment by hsb1007** [comment]
Can you explain how this works?

**Comment by tungmt** [comment]
First you need to use admin api with api ```add-version``` to add new version info with ```is_required=true```

Then in the app will display the popup that cannot close and force user to update to new version until current app match new version.

![Image](https://github.com/user-attachments/assets/b802908d-4f52-4edf-a2ce-781bb6aeae7c)

**Comment by hsb1007** [comment]
Love it
