### ISSUE TITLE
Adding social icons in email template

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/mobile-app#87]
https://www.instagram.com/kuky_app/
https://www.tiktok.com/@kuky_app
https://www.youtube.com/@kuky_app
https://x.com/kuky_app
https://facebook.com/kukyapp
https://wa.me/610491711556

**Comment by hsb1007** [comment]
I don't see the link set up for all

![Image](https://github.com/user-attachments/assets/e639f642-b681-4005-8f40-edbc51d8d355)

**Comment by tungmt** [comment]
Yes, please check because in the design we have only these icon

**Comment by hsb1007** [comment]
![Image](https://github.com/user-attachments/assets/27eafd83-5b58-4339-a9dd-a87389b94cc1)


Now they have been added
