### ISSUE TITLE
Onboarding Screen & Matching Screen to be updated with the latest Figma

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/mobile-app#88]
![Image](https://github.com/user-attachments/assets/8454902b-a32d-4723-8868-4f3fca2d8101)

This is when the profile onboarding is completed

![Image](https://github.com/user-attachments/assets/5547bf56-86cc-4844-8104-2728b661ee41)

This is when the matching is successful

**Comment by tungmt** [comment]
@hsb1007 I cannot find new onboarding screen in figma. Can you send me the link?
